version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.12"
   jobs:
      post_create_environment:
         - python -m pip install uv
         - uv sync --extra dev

sphinx:
   configuration: docs/conf.py
   builder: dirhtml
